from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.pagesizes import letter

from datetime import datetime


def generate_report(
    fusion_result,
    voice_result,
    spiral_result,
    datscan_result,
    explanation,
    output_path="report.pdf"
):

    # -----------------------------------
    # CREATE PDF
    # -----------------------------------

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    elements = []

    # -----------------------------------
    # TITLE
    # -----------------------------------

    title = Paragraph(
        "Parkinson AI Diagnostic Report",
        styles["Title"]
    )

    elements.append(title)

    elements.append(
        Spacer(1, 20)
    )

    # -----------------------------------
    # TIMESTAMP
    # -----------------------------------

    timestamp = Paragraph(
        f"Generated: {datetime.now()}",
        styles["BodyText"]
    )

    elements.append(timestamp)

    elements.append(
        Spacer(1, 20)
    )

    # -----------------------------------
    # FINAL PREDICTION
    # -----------------------------------

    final_prediction = fusion_result.get(
        "final_prediction",
        "Unknown"
    )

    final_probability = fusion_result.get(
        "final_probability",
        0
    )

    prediction_text = f"""
    <b>Final Prediction:</b> {final_prediction}
    <br/>
    <b>Confidence:</b> {round(final_probability * 100, 2)}%
    """

    prediction_paragraph = Paragraph(
        prediction_text,
        styles["BodyText"]
    )

    elements.append(prediction_paragraph)

    elements.append(
        Spacer(1, 20)
    )

    # -----------------------------------
    # MODALITY RESULTS
    # -----------------------------------

    voice_text = f"""
    <b>Voice Biomarkers:</b>
    Parkinson Probability =
    {round(voice_result['parkinsons_probability'] * 100, 2)}%
    """

    spiral_text = f"""
    <b>Spiral Analysis:</b>
    Prediction =
    {spiral_result['prediction']}
    <br/>
    Confidence =
    {round(spiral_result['confidence'] * 100, 2)}%
    """

    datscan_text = f"""
    <b>DATScan Imaging:</b>
    Prediction =
    {datscan_result['prediction']}
    <br/>
    Confidence =
    {round(datscan_result['confidence'] * 100, 2)}%
    """

    elements.append(
        Paragraph(voice_text, styles["BodyText"])
    )

    elements.append(
        Spacer(1, 12)
    )

    elements.append(
        Paragraph(spiral_text, styles["BodyText"])
    )

    elements.append(
        Spacer(1, 12)
    )

    elements.append(
        Paragraph(datscan_text, styles["BodyText"])
    )

    elements.append(
        Spacer(1, 20)
    )

    # -----------------------------------
    # EXPLANATION
    # -----------------------------------

    explanation_title = Paragraph(
        "<b>AI Clinical Interpretation</b>",
        styles["Heading2"]
    )

    elements.append(explanation_title)

    elements.append(
        Spacer(1, 10)
    )

    explanation_paragraph = Paragraph(
        explanation,
        styles["BodyText"]
    )

    elements.append(explanation_paragraph)

    elements.append(
        Spacer(1, 30)
    )

    # -----------------------------------
    # FOOTER
    # -----------------------------------

    footer = Paragraph(
        "Generated by Parkinson AI Platform",
        styles["Italic"]
    )

    elements.append(footer)

    # -----------------------------------
    # BUILD PDF
    # -----------------------------------

    doc.build(elements)

    return output_path